// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmevvvdfokqmzajmprcy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtZXZ2dmRmb2txbXpham1wcmN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzgzODcsImV4cCI6MjA2MzQxNDM4N30.LFZD1xBXcyuNvmdn0kUIUTw6HrT7_832t4dTIhSc9uA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);